import Ecto.Query

alias Ex338.Accounts.User
alias Ex338.CalendarAssistant
alias Ex338.Championships
alias Ex338.Championships.Championship
alias Ex338.Championships.ChampionshipResult
alias Ex338.Championships.ChampionshipSlot
alias Ex338.Championships.ChampWithEventsResult
alias Ex338.DraftPicks
alias Ex338.DraftPicks.Admin
alias Ex338.DraftPicks.DraftPick
alias Ex338.DraftQueues
alias Ex338.DraftQueues.DraftQueue
alias Ex338.FantasyLeagues
alias Ex338.FantasyLeagues.FantasyLeague
alias Ex338.FantasyPlayers
alias Ex338.FantasyPlayers.FantasyPlayer
alias Ex338.FantasyPlayers.SportsLeague
alias Ex338.FantasyTeams
alias Ex338.FantasyTeams.FantasyTeam
alias Ex338.FantasyTeams.Owner
alias Ex338.InjuredReserves
alias Ex338.InSeasonDraftPicks
alias Ex338.Mailer
alias Ex338.NotificationEmail
alias Ex338.Repo
alias Ex338.RosterPositions
alias Ex338.RosterPositions.Admin
alias Ex338.RosterPositions.RosterPosition
alias Ex338.Trades
alias Ex338.Trades.Trade
alias Ex338.Trades.TradeLineItem
alias Ex338.Waivers
alias Ex338.Waivers.Admin
alias Ex338.Waivers.Waiver
