alias Ex338.{
  Accounts.User,
  CalendarAssistant,
  Championships,
  Championships.Championship,
  Championships.ChampionshipResult,
  Championships.ChampWithEventsResult,
  Championships.ChampionshipSlot,
  DraftPicks,
  DraftPicks.Admin,
  DraftPicks.DraftPick,
  DraftQueues,
  DraftQueues.DraftQueue,
  FantasyLeagues,
  FantasyLeagues.FantasyLeague,
  FantasyPlayers,
  FantasyPlayers.FantasyPlayer,
  FantasyPlayers.SportsLeague,
  FantasyTeams,
  FantasyTeams.FantasyTeam,
  FantasyTeams.Owner,
  InSeasonDraftPicks,
  InjuredReserves,
  Mailer,
  NotificationEmail,
  Repo,
  RosterPositions,
  RosterPositions.Admin,
  RosterPositions.RosterPosition,
  Trades,
  Trades.Trade,
  Trades.TradeLineItem,
  Waivers,
  Waivers.Admin,
  Waivers.Waiver
}

import Ecto.Query
