import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ex338, Ex338Web.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"
config :ex338, plausible_analytics: true

# Do not print debug messages in production
config :logger, level: :info

# Tzdata's autoupdate is left on deliberately. Disabling it to save boot time
# pinned production to the 2025a release bundled with tzdata 1.1.3 — older than
# the 2026c the updater had been fetching on each boot, with no newer :tzdata to
# bump to. Correct timezone data beats a faster restart.
#
# The cost is real: Render's filesystem is ephemeral, so the download and rebuild
# happens on every boot (~15s) and never persists. If that matters again, bake the
# release into the artifact from build.sh — the data lands in _build/prod/lib/
# tzdata/priv, which mix release packages — rather than freezing the data.

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
